### ISSUE TITLE
Does not support empty password

### ISSUE THREAD

**Issue by chryschabs** [eventEmitter/pg-tools#1]
Line 25 of PgTools.js shows !option.password, it will throw an error but it's inconvenient if my db is configured for no password for this user, can't use this user, for now I have to pass in a blank string instead.

Also support for -i option was removed so library no longer works with latest version of pg_dump, it will now throw error.

Seeing how simple the lib was though, im just gonna go ahead and inspire from what you did to run my pg_dump process locally instead of doing a pull request, still i thought you'd want to know these details.

pg_dump: invalid option -- i
Try "pg_dump --help" for more information.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'pg_dump -

**Comment by linaGirl** [comment]
sorry for the very late response. the repository is not maintained actively. you may open a pull request with the changes you have in mind.
